import {Geist, Geist_Mono, Satisfy} from "next/font/google";
import "./globals.css";
import { Parisienne, Marck_Script } from 'next/font/google'

const marck = Marck_Script({
    subsets: ['latin', 'cyrillic'],
    weight: ['400'],
    variable: '--font-marck'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Янульке 25",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marck.variable} ${geistMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
